name: On release prod

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Check current branch
        run: git status
      - name: Make file executable
        run: chmod +x ./builder.sh
      - name: Build image
        run: ./builder.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
